### PR TITLE
50x responses, and other fixes

### PR DESCRIPTION
**Pull request by nicklevine**
Handle 50x responses. Pass amz security headers to head requests. Readers for interrogating response objects

### CODE REVIEW

**Comment by xach** [comment]
Indentation in https://github.com/xach/zs3/pull/20/commits/64949b160d9d99d63c28322736aafee067a766c5 looks off - tab damage, or just needs reindenting?

**Comment by nicklevine** [comment]
Source of confusion located. Following commit (1324a84) on
interface.lisp removes two spaces from that line, taking indentation
from 4 spaces down to 2. Apologies for the confusion.

**Comment by quicklisp** [comment]
Can you please fix the indentation?

Just looked at the doc changes. A couple things:

* User input should be **bold** in code examples
* There seems to be a code example for response property readers under the `*backoff*` variable documentation
* What type of condition is signaled?

**Comment by nicklevine** [comment]
As already noted (in my previous comment), the indentation was fixed by a subsequent commit which formed part of my original pull request -- it is still fixed and there's nothing else to do!

I have **bolded** user input in the code example, moved the example about responses to the head of the "Responses" section (and improved the wording), and both noted the condition name and exported the symbol concerned.

**Pull request merged**
